### ISSUE TITLE
ModuleNotFoundError: No module named 'MidiStructurer'

### ISSUE THREAD

**Issue by asigalov61** [Wally869/MidiGenerator#3]
Is this some module that is missing? I could not find it anywhere.

Thank you.

**Comment by Wally869** [comment]
MidiStructurer is actually my other repo MusiStrata. I thought the name wasn't fitting anymore so I changed it for release 1.0 but hadn't had the chance to fix the references in this repo, but this has been fixed in b8eebf80c286c07f34ee768b9de1e5ee12d01552

MusiStrata is not yet available on pip so you can get it from github.
Repository: https://github.com/Wally869/MusiStrata
Documentation: https://wally869.github.io/MusiStrata/
